export interface Release {
  id: string;
  title: string;
  artist: string;
  featuring?: string;
  album?: string;
  type: "SINGLE" | "EP" | "ALBUM";
  year: number;
  streams: string;
  coverColor: string;
  initials: string;
  coverImage: string;
  role: "primary" | "feature";
  genre?: string;
  duration?: string;
  trackCount?: number;
  featured?: boolean;
  explicit?: boolean;
  spotifyUrl?: string;
  appleUrl?: string;
  youtubeUrl?: string;
  audiomackUrl?: string;
  previewUrl?: string;
}

export interface Project {
  id: string;
  title: string;
  type: "EP" | "ALBUM";
  year: number;
  released: string;
  label: string;
  trackCount: number;
  totalDuration: string;
  totalStreams: string;
  coverImage: string;
  coverColor: string;
  genre: string;
  features: string[];
  spotifyUrl?: string;
  appleUrl?: string;
  audiomackUrl?: string;
  featured: boolean;
}

export const releases: Release[] = [
  // ─── 2026 SINGLES ────────────────────────────────────────────────────────────
  {
    id: "1",
    title: "Stopit",
    artist: "OliveTheBoy",
    featuring: "Medikal",
    type: "SINGLE",
    year: 2026,
    streams: "800K+",
    coverColor: "#0d1a12",
    initials: "OTB",
    coverImage: "/olive/stopit.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "3:10",
    featured: true,
    explicit: false,
    spotifyUrl:
      "https://open.spotify.com/track/6JBxA9ofuX7OIY4ghOvuIY?si=d7a5cd388e944f54",
    appleUrl: "https://music.apple.com/us/song/stopit-feat-medikal/6788411506",
    youtubeUrl: "https://youtu.be/kvKefQooCKQ?si=EHxTat7hzAlG-xb-",
    audiomackUrl: "https://audiomack.com/olivetheboy_/song/stopit",
    previewUrl:
      "https://open.spotify.com/track/6JBxA9ofuX7OIY4ghOvuIY?si=d7a5cd388e944f54",
  },
  {
    id: "2",
    title: "Daashi (Caashi)",
    artist: "OliveTheBoy",
    featuring: "Beeztrap KOTM, LAMI JNR & Pinto Black",
    type: "SINGLE",
    year: 2026,
    streams: "800K+",
    coverColor: "#0d1a12",
    initials: "OTB",
    coverImage: "/olive/dashi.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "3:10",
    featured: true,
    explicit: false,
    spotifyUrl:
      "https://open.spotify.com/track/6cMPtuGUIOgmzmeejw7xXp?si=c5a98ee6ed464d27",
    appleUrl:
      "https://music.apple.com/us/song/daashi-caashi-feat-beeztrap-kotm-lami-jnr-pinto-black/6768432102",
    youtubeUrl: "https://www.youtube.com/watch?v=de89S8x2ywU",
    audiomackUrl: "https://audiomack.com/olivetheboy_/song/daashi-caashi",
    previewUrl:
      "https://open.spotify.com/track/6cMPtuGUIOgmzmeejw7xXp?si=c5a98ee6ed464d27",
  },

  // ─── 2025 EP — OUT OF THE BLUE ──────────────────────────────────────────────
  {
    id: "90",
    title: "Lala",
    artist: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "3M+",
    coverColor: "#071520",
    initials: "OTB",
    coverImage: "/olive/lala.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "2:37",
    featured: false,
    explicit: false,
    spotifyUrl:
      "https://open.spotify.com/track/7a7g1jbp3bgY5Nijlgfr6Q?si=76eeeeff18ee4d1f",
    appleUrl: "https://music.apple.com/us/song/lala/1882847251",
    youtubeUrl: "https://youtu.be/GCLoSSkC9v8?si=iARXWjBnOoDH7IDG",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    previewUrl:
      "https://open.spotify.com/track/7a7g1jbp3bgY5Nijlgfr6Q?si=76eeeeff18ee4d1f",
  },
  {
    id: "12",
    title: "Spidomita",
    artist: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "3M+",
    coverColor: "#071520",
    initials: "OTB",
    coverImage: "/olive/olive3.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "2:37",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: "4",
    title: "Convo",
    artist: "OliveTheBoy",
    featuring: "Veola",
    album: "Out of the Blue",
    type: "SINGLE",
    year: 2025,
    streams: "3M+",
    coverColor: "#071520",
    initials: "OTB",
    coverImage: "/olive/olive4.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "2:37",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: "5",
    title: "Bend",
    artist: "OliveTheBoy",
    featuring: "Sarkodie",
    album: "Out of the Blue",
    type: "EP",
    year: 2025,
    streams: "5M+",
    coverColor: "#071520",
    initials: "OTB",
    coverImage: "/olive/olive4.png",
    role: "primary",
    genre: "Afrobeats / Hip-hop",
    duration: "3:12",
    featured: false,
    explicit: true,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },
  {
    id: "6",
    title: "Tattoo",
    artist: "OliveTheBoy",
    album: "Out of the Blue",
    type: "EP",
    year: 2025,
    streams: "4M+",
    coverColor: "#071520",
    initials: "OTB",
    coverImage: "/olive/olive4.png",
    role: "primary",
    genre: "Afrobeats / Pop",
    duration: "2:34",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  },
  {
    id: "7",
    title: "Design",
    artist: "OliveTheBoy",
    featuring: "Soundz",
    album: "Out of the Blue",
    type: "EP",
    year: 2025,
    streams: "2M+",
    coverColor: "#071520",
    initials: "OTB",
    coverImage: "/olive/olive4.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "3:08",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  },
  {
    id: "8",
    title: "Survivor",
    artist: "OliveTheBoy",
    featuring: "Qing Madi",
    album: "Out of the Blue",
    type: "EP",
    year: 2025,
    streams: "3.5M+",
    coverColor: "#071520",
    initials: "OTB",
    coverImage: "/olive/olive4.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "2:33",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  },
  {
    id: "9",
    title: "One Bebe",
    artist: "OliveTheBoy",
    album: "Out of the Blue",
    type: "EP",
    year: 2025,
    streams: "2M+",
    coverColor: "#071520",
    initials: "OTB",
    coverImage: "/olive/olive4.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "2:39",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
  },
  {
    id: "11",
    title: "Trees",
    artist: "OliveTheBoy",
    album: "Out of the Blue",
    type: "EP",
    year: 2025,
    streams: "2.5M+",
    coverColor: "#071520",
    initials: "OTB",
    coverImage: "/olive/olive4.png",
    role: "primary",
    genre: "Afrobeats / Soul",
    duration: "2:50",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    previewUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
  },

  {
    id: "10",
    title: "A Fuul",
    artist: "OliveTheBoy",
    featuring: "Mayorkun",
    type: "SINGLE",
    year: 2025,
    streams: "4M+",
    coverColor: "#071520",
    initials: "OTB",
    coverImage: "/olive/a-fuul.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "2:45",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    previewUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
  },

  // ─── 2025 SINGLES ────────────────────────────────────────────────────────────
  {
    id: "13",
    title: "Wondaboy",
    artist: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "1.5M+",
    coverColor: "#1a0800",
    initials: "OTB",
    coverImage: "/olive/wondaboy.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "3:05",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
  },

  // ─── 2024 EP — AVANA DELUXE ──────────────────────────────────────────────────
  {
    id: "14",
    title: "Asylum",
    artist: "OliveTheBoy",
    album: "Avana (Deluxe)",
    type: "EP",
    year: 2024,
    streams: "10M+",
    coverColor: "#0e1a0a",
    initials: "OTB",
    coverImage: "/olive/asylum.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "3:18",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
  },
  {
    id: "15",
    title: "Home Alone",
    artist: "OliveTheBoy",
    album: "Avana (Deluxe)",
    type: "EP",
    year: 2024,
    streams: "4M+",
    coverColor: "#0e1a0a",
    initials: "OTB",
    coverImage: "/olive/asylum.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "3:02",
    featured: false,
    explicit: false,
    spotifyUrl: "https://open.spotify.com/track/0Tpc21BWeK5R8KN6wyuj7I",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
  },
  {
    id: "16",
    title: "GoodSin (Remix)",
    artist: "OliveTheBoy",
    featuring: "King Promise, Oxlade & Reekado Banks",
    album: "Avana (Deluxe)",
    type: "EP",
    year: 2023,
    streams: "8M+",
    coverColor: "#0e1a0a",
    initials: "OTB",
    coverImage: "/olive/asylum.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "3:30",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
  },

  // ─── 2023 EP — AVANA ────────────────────────────────────────────────────────
  {
    id: "17",
    title: "Nba",
    artist: "OliveTheBoy",
    album: "Avana",
    type: "EP",
    year: 2023,
    streams: "20M+",
    coverColor: "#162408",
    initials: "OTB",
    coverImage: "/olive/avana.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "3:15",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-17.mp3",
  },
  {
    id: "20",
    title: "360",
    artist: "OliveTheBoy",
    album: "Avana",
    type: "EP",
    year: 2023,
    streams: "3M+",
    coverColor: "#162408",
    initials: "OTB",
    coverImage: "/olive/avana.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "2:44",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-20.mp3",
  },
  {
    id: "21",
    title: "Goodsin",
    artist: "OliveTheBoy",
    album: "Avana",
    type: "EP",
    year: 2023,
    streams: "6M+",
    coverColor: "#162408",
    initials: "OTB",
    coverImage: "/olive/avana.png",
    role: "primary",
    genre: "Afrobeats / Soul",
    duration: "2:58",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
  {
    id: "19",
    title: "Stay",
    artist: "OliveTheBoy",
    album: "Avana",
    type: "EP",
    year: 2023,
    streams: "4M+",
    coverColor: "#162408",
    initials: "OTB",
    coverImage: "/olive/avana.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "3:00",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-19.mp3",
  },
  {
    id: "18",
    title: "JE",
    artist: "OliveTheBoy",
    album: "Avana",
    type: "EP",
    year: 2023,
    streams: "5M+",
    coverColor: "#162408",
    initials: "OTB",
    coverImage: "/olive/avana.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "2:50",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-18.mp3",
  },

  {
    id: "22",
    title: "Confession",
    artist: "OliveTheBoy",
    album: "Avana",
    type: "EP",
    year: 2023,
    streams: "2M+",
    coverColor: "#162408",
    initials: "OTB",
    coverImage: "/olive/avana.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "2:40",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  },

  // ─── 2021 EP — TANGA-REEN ────────────────────────────────────────────────────
  {
    id: "23",
    title: "Only You",
    artist: "OliveTheBoy",
    album: "Tanga-Reen",
    type: "EP",
    year: 2021,
    streams: "1M+",
    coverColor: "#1a150a",
    initials: "OTB",
    coverImage: "/olive/tangareen.png",
    role: "primary",
    genre: "Afrobeats",
    duration: "2:55",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: "24",
    title: "All on you",
    artist: "OliveTheBoy",
    album: "Tanga-Reen",
    type: "EP",
    year: 2021,
    streams: "800K+",
    coverColor: "#1a150a",
    initials: "OTB",
    coverImage: "/olive/tangareen.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "2:48",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: "24",
    title: "Saturday",
    artist: "OliveTheBoy",
    album: "Tanga-Reen",
    type: "EP",
    year: 2021,
    streams: "800K+",
    coverColor: "#1a150a",
    initials: "OTB",
    coverImage: "/olive/tangareen.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "2:48",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: "24",
    title: "Boys Boys",
    artist: "OliveTheBoy",
    album: "Tanga-Reen",
    type: "EP",
    year: 2021,
    streams: "800K+",
    coverColor: "#1a150a",
    initials: "OTB",
    coverImage: "/olive/tangareen.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "2:48",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: "24",
    title: "Hey Shody",
    artist: "OliveTheBoy",
    album: "Tanga-Reen",
    type: "EP",
    year: 2021,
    streams: "800K+",
    coverColor: "#1a150a",
    initials: "OTB",
    coverImage: "/olive/tangareen.png",
    role: "primary",
    genre: "Afrobeats / R&B",
    duration: "2:48",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },

  // ─── FEATURES ────────────────────────────────────────────────────────────────
  {
    id: "f1",
    title: "Crazy Love",
    artist: "Wendy Shay",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "500K+",
    coverColor: "#1a0d12",
    initials: "WS",
    coverImage: "/olive/crazy_love.png",
    role: "feature",
    genre: "Afropop",
    duration: "3:20",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },
  {
    id: "29",
    title: "Akua Broni",
    artist: "Moon Byni",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2026,
    streams: "4M+",
    coverColor: "#12100a",
    initials: "KP",
    coverImage: "/olive/akua-broni.png",
    role: "feature",
    genre: "Afrobeats / Highlife",
    duration: "3:22",
    featured: false,
    explicit: false,
    spotifyUrl: "#",
    appleUrl: "#",
    youtubeUrl: "#",
    audiomackUrl: "#",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
  },
  {
    id: "f3",
    title: "Gymnastic",
    artist: "KiDi",
    featuring: "OliveTheBoy & Kojo Blak",
    type: "SINGLE",
    year: 2025,
    streams: "1M+",
    coverColor: "#12150d",
    initials: "KD",
    coverImage: "/olive/gymnastics.png",
    role: "feature",
    genre: "Afropop",
    duration: "3:15",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },
  {
    id: "f9",
    title: "Too Bad",
    artist: "Medikal",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "900K+",
    coverColor: "#1a0d0d",
    initials: "MDK",
    coverImage: "/olive/too_bad.png",
    role: "feature",
    genre: "Afrobeats / Hiplife",
    duration: "3:12",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },

  {
    id: "f5",
    title: "Favourite Story",
    artist: "King Promise",
    featuring: "Sarkodie & OliveTheBoy",
    type: "SINGLE",
    year: 2024,
    streams: "2M+",
    coverColor: "#1a120d",
    initials: "KP",
    coverImage: "/olive/favorite_story.png",
    role: "feature",
    genre: "Afrobeats",
    duration: "3:30",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "https://audiomack.com/kingpromise/song/favourite-story",
    previewUrl: "",
  },
  {
    id: "f90",
    title: "YOU & I",
    artist: "Sarkodie",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2026,
    streams: "500K+",
    coverColor: "#1a120d",
    initials: "SK",
    coverImage: "/olive/you.png",
    role: "feature",
    genre: "Afrobeats",
    duration: "3:30",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "https://audiomack.com/kingpromise/song/favourite-story",
    previewUrl: "",
  },
  {
    id: "f2",
    title: "OMG",
    artist: "Mr Drew",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "400K+",
    coverColor: "#0d1218",
    initials: "MD",
    coverImage: "/olive/omg.png",
    role: "feature",
    genre: "Afrobeats",
    duration: "3:05",
    featured: false,
    explicit: false,
    spotifyUrl: "https://open.spotify.com/track/642UlSGtBqRt7RPW6p930B",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },
  {
    id: "f6",
    title: "Blacklist",
    artist: "Smallgod",
    featuring: "OliveTheBoy & M.I.K",
    type: "SINGLE",
    year: 2024,
    streams: "700K+",
    coverColor: "#0a0a0a",
    initials: "SG",
    coverImage: "/olive/blacklist.png",
    role: "feature",
    genre: "Afrobeats",
    duration: "3:10",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },
  {
    id: "f7",
    title: "Double Breakfast",
    artist: "DJ Breezy",
    featuring: "Camidoh & OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "800K+",
    coverColor: "#0d1218",
    initials: "DJB",
    coverImage: "/olive/double.png",
    role: "feature",
    genre: "Afrobeats / Dancehall",
    duration: "3:08",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },
  {
    id: "f8",
    title: "Leave You",
    artist: "Siifa",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "400K+",
    coverColor: "#120d1a",
    initials: "SF",
    coverImage: "/olive/leave_you.png",
    role: "feature",
    genre: "Afropop",
    duration: "3:00",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },

  {
    id: "f10",
    title: "Screaming Beauty",
    artist: "Shoday",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "1.2M+",
    coverColor: "#0d180d",
    initials: "SHD",
    coverImage: "/olive/screaming.png",
    role: "feature",
    genre: "Afrobeats",
    duration: "3:18",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },
  {
    id: "f11",
    title: "Would You?",
    artist: "Mayorkun",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "1.5M+",
    coverColor: "#0d1012",
    initials: "MYK",
    coverImage: "/olive/would_you.png",
    role: "feature",
    genre: "Afrobeats",
    duration: "3:22",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },
  {
    id: "f12",
    title: "Close To Me (Ghana Remix)",
    artist: "Niphkeys",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "600K+",
    coverColor: "#121218",
    initials: "NPK",
    coverImage: "/olive/close_to_me.png",
    role: "feature",
    genre: "Afrobeats",
    duration: "3:05",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },
  {
    id: "f13",
    title: "Emmanuella",
    artist: "DJ Neptune",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "800K+",
    coverColor: "#0d0d1a",
    initials: "DJN",
    coverImage: "/olive/emmanuella.png",
    role: "feature",
    genre: "Afrobeats",
    duration: "3:15",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },
  {
    id: "f14",
    title: "Mad",
    artist: "Soundz",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "500K+",
    coverColor: "#181212",
    initials: "SNZ",
    coverImage: "/olive/mad.png ",
    role: "feature",
    genre: "Afrobeats",
    duration: "3:10",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },

  {
    id: "f4",
    title: "Shut Up (Pretense)",
    artist: "Quamina MP",
    featuring: "OliveTheBoy",
    type: "SINGLE",
    year: 2025,
    streams: "600K+",
    coverColor: "#0d1a18",
    initials: "QMP",
    coverImage: "/olive/shut_up.png",
    role: "feature",
    genre: "Afro-fusion",
    duration: "3:00",
    featured: false,
    explicit: false,
    spotifyUrl: "",
    appleUrl: "",
    youtubeUrl: "",
    audiomackUrl: "",
    previewUrl: "",
  },
];

export const projects: Project[] = [
  {
    id: "ep-out-of-the-blue",
    title: "Out of the Blue",
    type: "EP",
    year: 2025,
    released: "April 11, 2025",
    label: "BuVision / Loop Music / Columbia Records",
    trackCount: 8,
    totalDuration: "22 min",
    totalStreams: "20M+",
    coverImage: "/olive/olive4.png",
    coverColor: "#071520",
    genre: "Afrobeats / Soul / Pop",
    features: ["Sarkodie", "Mayorkun", "Qing Madi", "Soundz", "Veola"],
    spotifyUrl: "#",
    appleUrl: "#",
    audiomackUrl: "https://audiomack.com/olivetheboy_/album/out-of-the-blue-1",
    featured: true,
  },
  {
    id: "ep-asylum",
    title: "Avana (Deluxe)",
    type: "EP",
    year: 2024,
    released: "2024",
    label: "BuVision / Loop Music / Columbia Records",
    trackCount: 8,
    totalDuration: "24 min",
    totalStreams: "25M+",
    coverImage: "/olive/asylum.png",
    coverColor: "#0e1a0a",
    genre: "Afrobeats / R&B",
    features: ["King Promise", "Oxlade", "Reekado Banks"],
    spotifyUrl: "#",
    appleUrl: "#",
    audiomackUrl: "#",
    featured: false,
  },
  {
    id: "ep-avana",
    title: "Avana",
    type: "EP",
    year: 2023,
    released: "May 2023",
    label: "Loop Music",
    trackCount: 6,
    totalDuration: "15 min",
    totalStreams: "30M+",
    coverImage: "/olive/avana.png",
    coverColor: "#162408",
    genre: "Afrobeats",
    features: [],
    spotifyUrl: "#",
    appleUrl: "#",
    audiomackUrl: "#",
    featured: false,
  },
  {
    id: "ep-tanga-reen",
    title: "Tanga-Reen",
    type: "EP",
    year: 2021,
    released: "2021",
    label: "Loop Music",
    trackCount: 5,
    totalDuration: "~14 min",
    totalStreams: "2M+",
    coverImage: "/olive/tangareen.png",
    coverColor: "#1a150a",
    genre: "Afrobeats",
    features: [],
    spotifyUrl: "#",
    appleUrl: "#",
    audiomackUrl: "#",
    featured: false,
  },
];
